modLoader = "javafml"
loaderVersion = "[51,)"
issueTrackerURL = "https://github.com/Octo-Studios/immersive-ui"
license = "ARR"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
Makes your UI flashy :D
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[51,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"