modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "immersiveui"
version = "${version}"
displayName = "ImmersiveUI"
authors = "Octo-Studios"
description = '''
Makes your UI flashy :D
'''
#logoFile = ""

[[dependencies.immersiveui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersiveui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.immersiveui]]
#modId = "architectury"
#mandatory = true
#versionRange = "[9.2.14,)"
#ordering = "AFTER"
#side = "BOTH"