plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.gradleup.shadow' version '8.3.6' apply false
    id("io.freefair.lombok") version "8.14.2" apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.mod_group
    version = rootProject.mod_version + "+" + rootProject.minecraft_version

    repositories {
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }
    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    apply plugin: 'io.freefair.lombok'

    base {
        archivesName = "$rootProject.mod_name" + "-" + "$project.name".toUpperCase()
    }

    repositories {
        mavenLocal()
        flatDir {
            dirs 'libs'
        }
        maven {
            name = "OctoStudios"
            url = uri("https://maven.octo-studios.com/releases")
        }
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"

        loom {
            silentMojangMappingsLicense()
        }

        mappings loom.layered() {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-1.21.9:2025.10.05@zip")
        }

        implementation 'org.jetbrains:annotations:20.1.0'

        if (file("libs").isDirectory()) {
            file("libs").eachFile { file ->
                def splitPos = file.name.lastIndexOf("-")

                if (file.name != "desktop.ini") {
                    println file.name

                    def modartifact = file.name.substring(0, splitPos)
                    def modversion = file.name.substring(splitPos + 1, file.name.length() - 4)
                    def modreference = "lib:$modartifact:$modversion"

                    if ("$project.name".equalsIgnoreCase("neoforge")) {
                        dependencies {
                            implementation (project.dependencies.create(modreference) {
                                transitive = false
                            })
                        }
                    } else if ("$project.name".equalsIgnoreCase("fabric")) {
                        dependencies {
                            modImplementation project.dependencies.create(modreference);
                        }
                    } else {
                        dependencies {
                            modImplementation project.dependencies.create(modreference);
                        }
                    }

                }
            }
        } else file("libs").mkdir()
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    publishing {
        repositories {
            maven {
                name = "octo"
                url = "https://maven.octo-studios.com/releases"
                credentials(PasswordCredentials)
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
        publications {
            maven(MavenPublication) {
                groupId = group
                artifactId = project.mod_id + "-" + project.name
                version = version + "+" + project.minecraft_version
                from components.java
            }
        }
    }
}
