modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Octo-Studios/immersive-ui"
license = "ARR"

[[mixins]]
config = "${mod_id}-common.mixins.json"
[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
Makes your UI flashy :D
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[21.0.6-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"